### ISSUE TITLE
quick question about performance

### ISSUE THREAD

**Issue by bc** [amoffat/tf-jitsi#1]
Hi! Thanks so much for setting this repo up.

 I'm working on an application that has N groups of 4 participants, and I want to get an idea of how many groups one EC2 instance can support (and the pricing).

Based on your experience, could you give an example of an EC2 instance size, and the number of participants you've successfully had a call with on this infrastructure?

**Comment by amoffat** [comment]
A `m5dn.xlarge`, which is $0.27/hr and supports up to 25Gbit networking, used 40% cpu with 9 participants and peaked 13Mbit/s incoming, 23Mbit/s outgoing network. AWS bills $0.09/GB for outbound, and 9 participants for 1.5 hours accrued 20GB outbound. Hope that helps.

**Comment by bc** [comment]
That helps a ton! Are there any server-side settings I can tune to force all clients to send a lower quality video? Or is the adaptive compression done on the EC2 instance?

**Comment by amoffat** [comment]
You'll have to look at the [jitsi configs](https://github.com/jitsi/jitsi-meet/blob/master/config.js#L103-L121) for that. There are some things you can tune, but I didn't mess with them much.  IIRC, the jitsi component that serves as the video feed hub (jvb or "videobridge") just passes through the feeds as-is, which is how jitsi can have low cpu usage even on low end machines.
