### ISSUE TITLE
Dropping calls and degraded performance

### ISSUE THREAD

**Issue by justanotherspy** [amoffat/tf-jitsi#2]
Hi there thanks so much for the scripts and instructions. I tried this out using the new Cape Town region (which is local for me). And I just had to fetch the AMI ID and add it to the list of AMIs for the af-south-1 region. It worked after that.

However with some testing using 2 different instance types (t3.small and c5.large) I see a fairly sudden drop in quality after a few seconds of a call followed by continuous disconnecting. I tried this with 2 different callers in different locations. I don't think its a WiFi issue but I could be wrong. Has anyone managed to get really good performance from Jitsi? Because continuous disconnects makes it unusable. 

Looking to setup an alternative to Zoom however if performance isn't good enough even with large local servers and low call volume then is there hope for self-hosting at all? 

Thanks!

**Comment by amoffat** [comment]
Hi Daniel, happy to hear it worked for you. Regarding quality, it tends to improve mysteriously the more people you have on the call. I don't know about the disconnects though, I didn't experience many of those.
